/*!
Copyright 2012-2026 Sarven Capadisli <https://csarven.ca/>
Copyright 2023-2026 Virginia Balseiro <https://virginiabalseiro.com/>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import rdf from 'rdf-ext';
import Config from './config.js';
import { getResource } from './fetcher.js';
import { getResourceGraph } from './graph.js';
import { scoreMatch } from './util.js';

// Properties dokieli already emits, so the common case resolves offline and
// ranks above anything the remote sources return.
const LOCAL_TERMS = [
  ['dcterms:title', 'title'],
  ['dcterms:creator', 'creator'],
  ['dcterms:contributor', 'contributor'],
  ['dcterms:publisher', 'publisher'],
  ['dcterms:created', 'created', 'date'],
  ['dcterms:modified', 'modified', 'date'],
  ['dcterms:issued', 'issued', 'date'],
  ['dcterms:date', 'date', 'date'],
  ['dcterms:description', 'description'],
  ['dcterms:subject', 'subject'],
  ['dcterms:identifier', 'identifier'],
  ['dcterms:license', 'license'],
  ['dcterms:language', 'language'],
  ['dcterms:source', 'source'],
  ['dcterms:hasPart', 'has part'],
  ['dcterms:isPartOf', 'is part of'],
  ['dcterms:rights', 'rights'],
  ['dcterms:abstract', 'abstract'],

  ['schema:name', 'name'],
  ['schema:headline', 'headline'],
  ['schema:description', 'description'],
  ['schema:author', 'author'],
  ['schema:creator', 'creator'],
  ['schema:contributor', 'contributor'],
  ['schema:editor', 'editor'],
  ['schema:publisher', 'publisher'],
  ['schema:datePublished', 'date published', 'date'],
  ['schema:dateCreated', 'date created', 'date'],
  ['schema:dateModified', 'date modified', 'date'],
  ['schema:url', 'url', 'anyURI'],
  ['schema:image', 'image', 'anyURI'],
  ['schema:isbn', 'ISBN'],
  ['schema:issn', 'ISSN'],
  ['schema:numberOfPages', 'number of pages', 'integer'],
  ['schema:bookEdition', 'book edition'],
  ['schema:inLanguage', 'in language'],
  ['schema:genre', 'genre'],
  ['schema:keywords', 'keywords'],
  ['schema:about', 'about'],
  ['schema:citation', 'citation'],
  ['schema:identifier', 'identifier'],
  ['schema:email', 'email'],
  ['schema:telephone', 'telephone'],
  ['schema:address', 'address'],
  ['schema:birthDate', 'birth date', 'date'],
  ['schema:jobTitle', 'job title'],
  ['schema:worksFor', 'works for'],
  ['schema:owns', 'owns'],
  ['schema:price', 'price', 'decimal'],
  ['schema:priceCurrency', 'price currency'],
  ['schema:ratingValue', 'rating value', 'decimal'],
  ['schema:duration', 'duration', 'duration'],
  ['schema:distance', 'distance'],
  ['schema:speed', 'speed'],
  ['schema:startDate', 'start date', 'date'],
  ['schema:endDate', 'end date', 'date'],
  ['schema:location', 'location'],
  ['schema:latitude', 'latitude', 'decimal'],
  ['schema:longitude', 'longitude', 'decimal'],
  ['schema:elevation', 'elevation', 'decimal'],
  ['schema:hasPart', 'has part'],
  ['schema:isPartOf', 'is part of'],
  ['schema:sameAs', 'same as'],
  ['schema:status', 'status'],
  ['schema:version', 'version'],

  ['rdf:type', 'type'],
  ['rdfs:label', 'label'],
  ['rdfs:comment', 'comment'],
  ['rdfs:seeAlso', 'see also'],
  ['rdfs:isDefinedBy', 'is defined by'],
  ['owl:sameAs', 'same as'],

  ['foaf:name', 'name'],
  ['foaf:givenName', 'given name'],
  ['foaf:familyName', 'family name'],
  ['foaf:nick', 'nickname'],
  ['foaf:homepage', 'homepage'],
  ['foaf:mbox', 'mailbox'],
  ['foaf:img', 'image'],
  ['foaf:knows', 'knows'],
  ['foaf:based_near', 'based near'],

  ['skos:prefLabel', 'preferred label'],
  ['skos:altLabel', 'alternative label'],
  ['skos:definition', 'definition'],
  ['skos:broader', 'broader'],
  ['skos:narrower', 'narrower'],
  ['skos:related', 'related'],
  ['skos:notation', 'notation'],

  ['bibo:isbn', 'ISBN'],
  ['bibo:issn', 'ISSN'],
  ['bibo:doi', 'DOI'],
  ['bibo:volume', 'volume'],
  ['bibo:issue', 'issue'],
  ['bibo:pageStart', 'page start'],
  ['bibo:pageEnd', 'page end'],
  ['bibo:numPages', 'number of pages', 'integer'],
  ['bibo:edition', 'edition'],

  ['prov:wasGeneratedBy', 'was generated by'],
  ['prov:wasDerivedFrom', 'was derived from'],
  ['prov:wasAttributedTo', 'was attributed to'],
  ['prov:generatedAtTime', 'generated at time', 'dateTime'],

  ['as:actor', 'actor'],
  ['as:object', 'object'],
  ['as:published', 'published', 'dateTime'],
  ['as:summary', 'summary'],

  ['wgs:lat', 'latitude', 'decimal'],
  ['wgs:long', 'longitude', 'decimal'],
  ['wgs:alt', 'altitude', 'decimal'],

  ['qb:dataSet', 'data set'],
  ['qb:observation', 'observation'],
  ['qb:measureType', 'measure type']
];

let localIndex = null;

function getLocalIndex() {
  if (localIndex) return localIndex;

  localIndex = LOCAL_TERMS.map(([curie, label, datatype]) => {
    const [prefix, name] = curie.split(':');
    return {
      curie,
      iri: Config.ns[prefix] ? Config.ns[prefix](name).value : null,
      label,
      prefix,
      datatype: datatype ? `xsd:${datatype}` : null,
      source: 'dokieli'
    };
  });

  // Curated CiTO relations already carry human labels.
  Object.entries(Config.Citation || {}).forEach(([iri, label]) => {
    const curie = toCurie(iri);
    if (!curie || localIndex.some((t) => t.curie === curie)) return;
    localIndex.push({ curie, iri, label, prefix: curie.split(':')[0], datatype: null, source: 'dokieli' });
  });

  return localIndex;
}

export function toCurie(iri) {
  if (!iri || typeof iri !== 'string') return iri;
  if (!URL.canParse(iri)) return iri;

  // Longest namespace wins, so a prefix that is a substring of another
  // (dcelements vs dcterms) doesn't shadow it.
  const match = Object.entries(Config.ns)
    .map(([prefix, namespace]) => [prefix, namespace('').value])
    .filter(([, base]) => base && iri.startsWith(base) && iri.length > base.length)
    .sort((a, b) => b[1].length - a[1].length)[0];

  if (!match) return iri;

  return `${match[0]}:${iri.slice(match[1].length)}`;
}

export function searchLocalTerms(keyword) {
  const q = keyword.trim().toLowerCase();
  if (!q) return [];

  return getLocalIndex()
    .map((term) => ({
      term,
      score: Math.max(
        scoreMatch(q, term.label),
        scoreMatch(q, term.curie)
      )
    }))
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 10)
    .map(({ term }) => term);
}

// https://lov.linkeddata.es/dataset/lov/api
// XXX :Endpoint is too slow!
export async function searchLOVTerms(keyword, options = {}) {
  const termType = options.termType === 'class' ? 'class' : 'property';
  const url = `https://lov.linkeddata.es/dataset/lov/api/v2/term/search?q=${encodeURIComponent(keyword)}&type=${termType}&page_size=15`;

  try {
    const response = await getResource(url, { Accept: 'application/json' }, options);
    const data = await response.json();

    return (data?.results || []).map((r) => {
      const curie = first(r.prefixedName) || toCurie(first(r.uri));
      return {
        curie,
        iri: first(r.uri),
        label: first(r['prefixedName']) ? stripPrefix(curie) : first(r.uri),
        description: first(r['http://www.w3.org/2000/01/rdf-schema#comment']),
        prefix: first(r['vocabulary.prefix']),
        datatype: null,
        source: 'LOV'
      };
    }).filter((t) => t.curie);
  } catch (e) {
    console.warn('LOV term search failed:', e?.message || e);
    return [];
  }
}

// https://www.wikidata.org/w/api.php?action=help&modules=wbsearchentities
export async function searchWikidataProperties(keyword, options = {}) {
  const language = (Config.User?.UI?.Language || 'en').split('-')[0];
  const url = `https://www.wikidata.org/w/api.php?action=wbsearchentities&search=${encodeURIComponent(keyword)}&language=${language}&uselang=${language}&type=property&limit=10&format=json&origin=*`;

  try {
    const response = await getResource(url, { Accept: 'application/json' }, options);
    const data = await response.json();

    return (data?.search || []).map((r) => ({
      curie: `wdt:${r.id}`,
      iri: `http://www.wikidata.org/prop/direct/${r.id}`,
      label: r.label || r.id,
      description: r.description,
      prefix: 'wdt',
      datatype: null,
      source: 'Wikidata'
    }));
  } catch (e) {
    console.warn('Wikidata property search failed:', e?.message || e);
    return [];
  }
}

const PROPERTY_TYPES = [
  'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property',
  'http://www.w3.org/2002/07/owl#ObjectProperty',
  'http://www.w3.org/2002/07/owl#DatatypeProperty',
  'http://www.w3.org/2002/07/owl#AnnotationProperty'
];

const vocabularyCache = new Map();

// Dereference any RDFS/OWL vocabulary and offer its properties.
export async function loadVocabularyTerms(vocabularyUrl, options = {}) {
  if (vocabularyCache.has(vocabularyUrl)) return vocabularyCache.get(vocabularyUrl);

  const promise = (async () => {
    try {
      // getResourceGraph resolves { response, graph, error }; graph is a grapoi
      // pointer, not a dataset.
      const { graph, error } = await getResourceGraph(vocabularyUrl, null, options);
      if (error || !graph?.dataset) return [];

      const dataset = graph.dataset;
      const terms = new Map();

      for (const quad of dataset) {
        if (quad.predicate.value !== 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type') continue;
        if (!PROPERTY_TYPES.includes(quad.object.value)) continue;
        if (quad.subject.termType !== 'NamedNode') continue;

        const iri = quad.subject.value;
        if (terms.has(iri)) continue;

        const node = graph.node(quad.subject);
        const label =
          literalValue(node, 'http://www.w3.org/2000/01/rdf-schema#label') ||
          literalValue(node, 'http://www.w3.org/2004/02/skos/core#prefLabel') ||
          iri.split(/[#/]/).filter(Boolean).pop();

        terms.set(iri, {
          curie: toCurie(iri),
          iri,
          label,
          description: literalValue(node, 'http://www.w3.org/2000/01/rdf-schema#comment'),
          prefix: null,
          datatype: toCurie(objectValue(node, 'http://www.w3.org/2000/01/rdf-schema#range')),
          source: vocabularyUrl
        });
      }

      return [...terms.values()];
    } catch (e) {
      console.warn(`Could not load vocabulary ${vocabularyUrl}:`, e?.message || e);
      return [];
    }
  })();

  vocabularyCache.set(vocabularyUrl, promise);
  return promise;
}

function literalValue(node, predicate) {
  const preferred = (Config.User?.UI?.Language || 'en').split('-')[0];
  const values = [...node.out(rdf.namedNode(predicate)).terms].filter((t) => t.termType === 'Literal');
  const inLanguage = values.find((t) => t.language?.startsWith(preferred));
  return (inLanguage || values[0])?.value;
}

function objectValue(node, predicate) {
  return [...node.out(rdf.namedNode(predicate)).terms].find((t) => t.termType === 'NamedNode')?.value;
}

function first(value) {
  return Array.isArray(value) ? value[0] : value;
}

function stripPrefix(curie) {
  return typeof curie === 'string' && curie.includes(':') ? curie.split(':').slice(1).join(':') : curie;
}

/**
 * Search every enabled source. Local terms resolve synchronously and come
 * first; remote sources are merged in as they are available, deduplicated by
 * IRI so the local (labelled, datatype-carrying) entry wins.
 */
export async function searchProperties(keyword, options = {}) {
  const {
    // LOV is not searched by default: the endpoint is too slow for as-you-type search.
    sources = ['local', 'wikidata'],
    vocabularies = [],
    limit = 20
  } = options;

  const results = sources.includes('local') ? searchLocalTerms(keyword) : [];

  const pending = [];
  if (sources.includes('lov')) pending.push(searchLOVTerms(keyword, options));
  if (sources.includes('wikidata')) pending.push(searchWikidataProperties(keyword, options));

  vocabularies.forEach((url) => {
    pending.push(loadVocabularyTerms(url, options).then((terms) => filterTerms(terms, keyword)));
  });

  const settled = await Promise.allSettled(pending);
  settled.forEach((r) => {
    if (r.status === 'fulfilled') results.push(...r.value);
  });

  const seen = new Set();
  return results
    .filter((term) => {
      const key = term.iri || term.curie;
      if (!key || seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .slice(0, limit);
}

/** Classes rather than properties, for anything that asks for a type. */
export async function searchClasses(keyword, options = {}) {
  return searchProperties(keyword, {
    ...options,
    termType: 'class',
    // Wikidata's property search returns no classes.
    sources: (options.sources || ['local']).filter((s) => s !== 'wikidata')
  });
}

function filterTerms(terms, keyword) {
  const q = keyword.trim().toLowerCase();
  if (!q) return [];

  return terms
    .map((term) => ({
      term,
      score: Math.max(
        scoreMatch(q, String(term.label || '')),
        scoreMatch(q, String(term.curie || ''))
      )
    }))
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 10)
    .map(({ term }) => term);
}

// A picked term may use a prefix the document doesn't declare yet.
export function getPrefixForTerm(term) {
  if (!term?.curie?.includes(':')) return null;
  const prefix = term.curie.split(':')[0];
  return Config.ns[prefix] ? null : { prefix, iri: deriveNamespace(term.iri) };
}

function deriveNamespace(iri) {
  if (!iri) return null;
  const match = iri.match(/^(.*[#/])[^#/]+$/);
  return match ? match[1] : null;
}
